//! protogen: protocol/schema/messages.toml → protocol/generated/skyrimxer_protocol.{h,rs}.
//!
//! `cargo run -p protogen`           regenerate both files
//! `cargo run -p protogen -- --check` exit 1 if either file is stale (also run by `cargo test -p protogen`)
//!
//! The generator owns layout validation (natural alignment, no implicit padding, declared sizes, region overlaps),
//! and emits size/offset asserts so each compiler re-checks the same layout.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde::Deserialize;

const HEADER_NOTE: &str = "@generated by tools/protogen from protocol/schema/messages.toml. DO NOT EDIT.";

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Schema {
    protocol: Protocol,
    constants: toml::Table,
    enums: Vec<Enum>,
    structs: Vec<Struct>,
    region: Region,
    messages: Vec<Struct>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Protocol {
    version: u32,
    magic: String,
    region_name: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Constant {
    #[serde(rename = "type")]
    ty: String,
    value: i64,
    doc: Option<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Enum {
    name: String,
    repr: String,
    doc: Option<String>,
    values: Vec<EnumValue>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct EnumValue {
    name: String,
    value: i64,
    doc: Option<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Struct {
    name: String,
    size: Option<usize>,
    doc: Option<String>,
    fields: Vec<Field>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Field {
    name: String,
    #[serde(rename = "type")]
    ty: String,
    doc: Option<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Region {
    blocks: Vec<Block>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Block {
    name: String,
    offset: usize,
    #[serde(rename = "struct")]
    struct_name: Option<String>,
    bytes: Option<usize>,
}

#[derive(Clone, Copy)]
struct Prim {
    rust: &'static str,
    cpp: &'static str,
    size: usize,
}

fn prim(name: &str) -> Option<Prim> {
    let (rust, cpp, size) = match name {
        "u8" => ("u8", "std::uint8_t", 1),
        "u16" => ("u16", "std::uint16_t", 2),
        "u32" => ("u32", "std::uint32_t", 4),
        "u64" => ("u64", "std::uint64_t", 8),
        "i8" => ("i8", "std::int8_t", 1),
        "i16" => ("i16", "std::int16_t", 2),
        "i32" => ("i32", "std::int32_t", 4),
        "i64" => ("i64", "std::int64_t", 8),
        "f32" => ("f32", "float", 4),
        "f64" => ("f64", "double", 8),
        _ => return None,
    };
    Some(Prim { rust, cpp, size })
}

/// A field type after parsing: a primitive, optionally a fixed array of it.
struct FieldType {
    prim: Prim,
    count: Option<usize>,
}

impl FieldType {
    fn parse(ty: &str) -> Result<Self, String> {
        let (base, count) = match ty.split_once('[') {
            Some((base, rest)) => {
                let n = rest
                    .strip_suffix(']')
                    .and_then(|n| n.parse::<usize>().ok())
                    .filter(|&n| n > 0)
                    .ok_or_else(|| format!("bad array type `{ty}`"))?;
                (base, Some(n))
            }
            None => (ty, None),
        };
        let prim = prim(base).ok_or_else(|| format!("unknown type `{base}`"))?;
        Ok(Self { prim, count })
    }
    fn size(&self) -> usize {
        self.prim.size * self.count.unwrap_or(1)
    }
    fn rust(&self) -> String {
        match self.count {
            Some(n) => format!("[{}; {n}]", self.prim.rust),
            None => self.prim.rust.to_string(),
        }
    }
}

/// A validated struct: field offsets, size and alignment.
struct Layout<'a> {
    def: &'a Struct,
    fields: Vec<(&'a Field, FieldType, usize)>,
    size: usize,
    align: usize,
}

fn layout(def: &Struct) -> Result<Layout<'_>, String> {
    let mut fields = Vec::new();
    let mut names = BTreeSet::new();
    let (mut offset, mut align) = (0usize, 1usize);
    for field in &def.fields {
        if !names.insert(field.name.as_str()) {
            return Err(format!("{}.{}: duplicate field", def.name, field.name));
        }
        let ty = FieldType::parse(&field.ty).map_err(|e| format!("{}.{}: {e}", def.name, field.name))?;
        let a = ty.prim.size;
        if offset % a != 0 {
            return Err(format!(
                "{}.{} at offset {offset} is not {a}-byte aligned: add an explicit `_pad` field before it",
                def.name, field.name
            ));
        }
        align = align.max(a);
        let size = ty.size();
        fields.push((field, ty, offset));
        offset += size;
    }
    if fields.is_empty() {
        return Err(format!("{}: no fields", def.name));
    }
    if offset % align != 0 {
        return Err(format!("{}: size {offset} is not a multiple of its alignment {align}: add trailing padding", def.name));
    }
    if let Some(declared) = def.size {
        if declared != offset {
            return Err(format!("{}: declared size {declared} but fields add up to {offset}", def.name));
        }
    }
    Ok(Layout { def, fields, size: offset, align })
}

/// HEARTBEAT_TIMEOUT_MS → kHeartbeatTimeoutMs
fn cpp_const_name(screaming: &str) -> String {
    let mut out = String::from("k");
    for word in screaming.split('_').filter(|w| !w.is_empty()) {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.extend(chars.map(|c| c.to_ascii_lowercase()));
        }
    }
    out
}

fn hex(v: usize) -> String {
    format!("0x{v:X}")
}

struct Model<'a> {
    schema: &'a Schema,
    constants: Vec<(String, Constant)>,
    structs: Vec<Layout<'a>>,
    messages: Vec<Layout<'a>>,
    region_size: usize,
}

fn validate(schema: &Schema) -> Result<Model<'_>, String> {
    let p = &schema.protocol;
    if p.magic.len() != 4 || !p.magic.is_ascii() {
        return Err("protocol.magic must be 4 ASCII characters".into());
    }
    if !p.region_name.ends_with(&format!("_v{}", p.version)) {
        return Err(format!("protocol.region_name `{}` must end in _v{}", p.region_name, p.version));
    }

    let mut constants = Vec::new();
    for (name, value) in &schema.constants {
        let c: Constant = value.clone().try_into().map_err(|e| format!("constant {name}: {e}"))?;
        if prim(&c.ty).is_none() || c.ty.starts_with('f') {
            return Err(format!("constant {name}: type must be an integer type"));
        }
        constants.push((name.clone(), c));
    }

    for e in &schema.enums {
        if !matches!(e.repr.as_str(), "u8" | "u16" | "u32") {
            return Err(format!("enum {}: repr must be u8/u16/u32", e.name));
        }
        let mut seen = BTreeSet::new();
        for v in &e.values {
            if !seen.insert(v.value) {
                return Err(format!("enum {}: duplicate value {}", e.name, v.value));
            }
        }
    }

    let structs = schema.structs.iter().map(layout).collect::<Result<Vec<_>, _>>()?;
    let messages = schema.messages.iter().map(layout).collect::<Result<Vec<_>, _>>()?;

    let max_payload = constants.iter().find(|(n, _)| n == "MSG_MAX_PAYLOAD").map(|(_, c)| c.value as usize);
    let msg_type = schema.enums.iter().find(|e| e.name == "MsgType").ok_or("enum MsgType is required")?;
    for m in &messages {
        if !msg_type.values.iter().any(|v| v.name == m.def.name) {
            return Err(format!("message {} has no MsgType value of the same name", m.def.name));
        }
        if max_payload.is_some_and(|max| m.size > max) {
            return Err(format!("message {} is larger than MSG_MAX_PAYLOAD", m.def.name));
        }
    }
    for v in &msg_type.values {
        if !messages.iter().any(|m| m.def.name == v.name) {
            return Err(format!("MsgType {} has no [[messages]] payload", v.name));
        }
    }

    let mut spans: Vec<(usize, usize, &str)> = Vec::new();
    for b in &schema.region.blocks {
        let size = match (&b.struct_name, b.bytes) {
            (Some(s), None) => {
                let l = structs.iter().find(|l| &l.def.name == s).ok_or_else(|| format!("block {}: unknown struct {s}", b.name))?;
                if b.offset % l.align != 0 {
                    return Err(format!("block {}: offset not aligned for {s}", b.name));
                }
                l.size
            }
            (None, Some(bytes)) => bytes,
            _ => return Err(format!("block {}: give exactly one of `struct` or `bytes`", b.name)),
        };
        if b.offset % 8 != 0 {
            return Err(format!("block {}: offset must be 8-byte aligned", b.name));
        }
        spans.push((b.offset, b.offset + size, &b.name));
    }
    spans.sort();
    for pair in spans.windows(2) {
        if pair[0].1 > pair[1].0 {
            return Err(format!("region blocks {} and {} overlap", pair[0].2, pair[1].2));
        }
    }
    let region_size = spans.last().map(|s| s.1).ok_or("region has no blocks")?;

    Ok(Model { schema, constants, structs, messages, region_size })
}

fn magic_value(magic: &str) -> u32 {
    u32::from_le_bytes(magic.as_bytes().try_into().unwrap())
}

fn rust_doc(out: &mut String, indent: &str, doc: &Option<String>) {
    if let Some(doc) = doc {
        for line in doc.lines() {
            let _ = writeln!(out, "{indent}/// {line}");
        }
    }
}

fn cpp_doc(out: &mut String, indent: &str, doc: &Option<String>) {
    if let Some(doc) = doc {
        for line in doc.lines() {
            let _ = writeln!(out, "{indent}// {line}");
        }
    }
}

fn gen_rust(m: &Model) -> String {
    let p = &m.schema.protocol;
    let mut o = String::new();
    let _ = writeln!(o, "// {HEADER_NOTE}");
    let _ = writeln!(o, "// Included by protocol/src/lib.rs as `skyrimxer_protocol::proto`.\n");
    let _ = writeln!(o, "pub const VERSION: u32 = {};", p.version);
    let _ = writeln!(o, "/// {:?} as little-endian bytes.", p.magic);
    let _ = writeln!(o, "pub const MAGIC: u32 = 0x{:08X};", magic_value(&p.magic));
    let _ = writeln!(o, "pub const REGION_NAME: &str = {:?};\n", p.region_name);
    for (name, c) in &m.constants {
        rust_doc(&mut o, "", &c.doc);
        let _ = writeln!(o, "pub const {name}: {} = {};", c.ty, c.value);
    }
    let _ = writeln!(o);
    for b in &m.schema.region.blocks {
        let _ = writeln!(o, "pub const OFF_{}: usize = {};", b.name, hex(b.offset));
    }
    let _ = writeln!(o, "pub const REGION_SIZE: usize = {};", hex(m.region_size));

    for e in &m.schema.enums {
        let _ = writeln!(o);
        rust_doc(&mut o, "", &e.doc);
        let _ = writeln!(o, "#[repr({})]\n#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\npub enum {} {{", e.repr, e.name);
        for v in &e.values {
            rust_doc(&mut o, "    ", &v.doc);
            let _ = writeln!(o, "    {} = {},", v.name, v.value);
        }
        let _ = writeln!(o, "}}\n\nimpl {} {{", e.name);
        let _ = writeln!(o, "    pub const fn from_raw(value: {}) -> Option<Self> {{\n        match value {{", e.repr);
        for v in &e.values {
            let _ = writeln!(o, "            {} => Some(Self::{}),", v.value, v.name);
        }
        let _ = writeln!(o, "            _ => None,\n        }}\n    }}\n}}");
    }

    for (l, is_msg) in m.structs.iter().map(|l| (l, false)).chain(m.messages.iter().map(|l| (l, true))) {
        let name = &l.def.name;
        let _ = writeln!(o);
        rust_doc(&mut o, "", &l.def.doc);
        let _ = writeln!(o, "#[repr(C)]\n#[derive(Clone, Copy, Debug, PartialEq)]\npub struct {name} {{");
        for (f, ty, _) in &l.fields {
            rust_doc(&mut o, "    ", &f.doc);
            let _ = writeln!(o, "    pub {}: {},", f.name, ty.rust());
        }
        let _ = writeln!(o, "}}\n");
        let _ = writeln!(o, "impl Default for {name} {{\n    fn default() -> Self {{");
        let _ = writeln!(o, "        // SAFETY: only plain integer/float fields, so all-zero bytes are a valid value.");
        let _ = writeln!(o, "        unsafe {{ core::mem::zeroed() }}\n    }}\n}}\n");
        let _ = writeln!(o, "// SAFETY: repr(C), plain number fields only, no implicit padding (checked by protogen and below).");
        let _ = writeln!(o, "unsafe impl crate::Plain for {name} {{}}");
        if is_msg {
            let _ = writeln!(o, "\nimpl crate::Message for {name} {{\n    const TYPE: MsgType = MsgType::{name};\n}}");
        }
        let _ = writeln!(o, "\nconst _: () = {{");
        let _ = writeln!(o, "    assert!(core::mem::size_of::<{name}>() == {});", l.size);
        let _ = writeln!(o, "    assert!(core::mem::align_of::<{name}>() == {});", l.align);
        for (f, _, off) in &l.fields {
            let _ = writeln!(o, "    assert!(core::mem::offset_of!({name}, {}) == {off});", f.name);
        }
        let _ = writeln!(o, "}};");
    }
    o
}

fn gen_cpp(m: &Model) -> String {
    let p = &m.schema.protocol;
    let mut o = String::new();
    let _ = writeln!(o, "// {HEADER_NOTE}");
    let _ = writeln!(o, "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n#include <type_traits>\n");
    let _ = writeln!(o, "namespace sxer::proto\n{{");
    let _ = writeln!(o, "\tinline constexpr std::uint32_t kVersion = {};", p.version);
    let _ = writeln!(o, "\tinline constexpr std::uint32_t kMagic = 0x{:08X};  // {:?} as little-endian bytes", magic_value(&p.magic), p.magic);
    let _ = writeln!(o, "\tinline constexpr wchar_t kRegionName[] = L\"{}\";\n", p.region_name.replace('\\', "\\\\"));
    for (name, c) in &m.constants {
        cpp_doc(&mut o, "\t", &c.doc);
        let ty = prim(&c.ty).unwrap().cpp;
        let _ = writeln!(o, "\tinline constexpr {ty} {} = {};", cpp_const_name(name), c.value);
    }
    let _ = writeln!(o);
    for b in &m.schema.region.blocks {
        let _ = writeln!(o, "\tinline constexpr std::size_t {} = {};", cpp_const_name(&format!("OFF_{}", b.name)), hex(b.offset));
    }
    let _ = writeln!(o, "\tinline constexpr std::size_t kRegionSize = {};", hex(m.region_size));

    for e in &m.schema.enums {
        let _ = writeln!(o);
        cpp_doc(&mut o, "\t", &e.doc);
        let _ = writeln!(o, "\tenum class {} : {}\n\t{{", e.name, prim(&e.repr).unwrap().cpp);
        for v in &e.values {
            let _ = write!(o, "\t\t{} = {},", v.name, v.value);
            match &v.doc {
                Some(doc) => {
                    let _ = writeln!(o, "  // {doc}");
                }
                None => o.push('\n'),
            }
        }
        let _ = writeln!(o, "\t}};");
    }

    for l in m.structs.iter().chain(m.messages.iter()) {
        let name = &l.def.name;
        let _ = writeln!(o);
        cpp_doc(&mut o, "\t", &l.def.doc);
        let _ = writeln!(o, "\tstruct {name}\n\t{{");
        for (f, ty, _) in &l.fields {
            let _ = write!(o, "\t\t{} {}", ty.prim.cpp, f.name);
            if let Some(n) = ty.count {
                let _ = write!(o, "[{n}]");
            }
            o.push(';');
            match &f.doc {
                Some(doc) => {
                    let _ = writeln!(o, "  // {doc}");
                }
                None => o.push('\n'),
            }
        }
        let _ = writeln!(o, "\t}};");
        let _ = writeln!(o, "\tstatic_assert(std::is_trivially_copyable_v<{name}> && std::is_standard_layout_v<{name}>);");
        let _ = writeln!(o, "\tstatic_assert(sizeof({name}) == {});", l.size);
        let _ = writeln!(o, "\tstatic_assert(alignof({name}) == {});", l.align);
        for (f, _, off) in &l.fields {
            let _ = writeln!(o, "\tstatic_assert(offsetof({name}, {}) == {off});", f.name);
        }
    }

    let _ = writeln!(o, "\n\t// Payload struct → MsgType, for typed send helpers.");
    let _ = writeln!(o, "\ttemplate <class T>\n\tstruct MsgTypeOf;");
    for l in &m.messages {
        let name = &l.def.name;
        let _ = writeln!(o, "\ttemplate <>\n\tstruct MsgTypeOf<{name}>\n\t{{\n\t\tstatic constexpr MsgType value = MsgType::{name};\n\t}};");
    }
    let _ = writeln!(o, "}}");
    o
}

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Returns (rust, cpp) source text generated from the schema on disk.
fn generate() -> Result<(String, String), String> {
    let path = root().join("protocol/schema/messages.toml");
    let text = fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
    let schema: Schema = toml::from_str(&text).map_err(|e| format!("messages.toml: {e}"))?;
    let model = validate(&schema)?;
    Ok((gen_rust(&model), gen_cpp(&model)))
}

fn outputs() -> [PathBuf; 2] {
    let dir = root().join("protocol/generated");
    [dir.join("skyrimxer_protocol.rs"), dir.join("skyrimxer_protocol.h")]
}

/// Paths whose contents differ from what the schema generates (line endings ignored).
fn stale_files() -> Result<Vec<PathBuf>, String> {
    let (rs, h) = generate()?;
    let mut stale = Vec::new();
    for (path, want) in outputs().into_iter().zip([rs, h]) {
        let have = fs::read_to_string(&path).unwrap_or_default().replace('\r', "");
        if have != want {
            stale.push(path);
        }
    }
    Ok(stale)
}

fn main() -> ExitCode {
    let check = std::env::args().any(|a| a == "--check");
    let result = if check {
        stale_files().map(|stale| {
            for path in &stale {
                eprintln!("stale: {} (run `cargo run -p protogen`)", path.display());
            }
            stale.is_empty()
        })
    } else {
        generate().and_then(|(rs, h)| {
            for (path, text) in outputs().into_iter().zip([rs, h]) {
                fs::write(&path, text).map_err(|e| format!("{}: {e}", path.display()))?;
                println!("wrote {}", path.display());
            }
            Ok(true)
        })
    };
    match result {
        Ok(true) => ExitCode::SUCCESS,
        Ok(false) => ExitCode::FAILURE,
        Err(e) => {
            eprintln!("protogen: {e}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_files_are_up_to_date() {
        let stale = stale_files().unwrap();
        assert!(stale.is_empty(), "stale generated files {stale:?}: run `cargo run -p protogen`");
    }

    #[test]
    fn implicit_padding_is_rejected() {
        let def = Struct {
            name: "Bad".into(),
            size: None,
            doc: None,
            fields: vec![
                Field { name: "a".into(), ty: "u8".into(), doc: None },
                Field { name: "b".into(), ty: "u32".into(), doc: None },
            ],
        };
        assert!(layout(&def).is_err());
    }

    #[test]
    fn cpp_names() {
        assert_eq!(cpp_const_name("OFF_RING_SKY_TO_ER_DATA"), "kOffRingSkyToErData");
    }
}
